/**
 * Source of new aggregate identifiers.
 *
 * Ids are generated by the application, not by the database, so a use case can
 * build a complete, valid aggregate before anything is persisted — and so the
 * choice of UUID, ULID or sequence stays an infrastructure decision.
 */
export interface IdGenerator {
  next(): string;
}
